Added input fields to the employment history section
objectcomputing/check-ins pull request #1854
Opened 2022-07-25 18:41 UTC by BenVuong

2022-07-25 19:48 UTC, MatthewBackes submitted a review, later dismissed

2022-07-27 20:18 UTC, MisheelSodgerel commented on onboard/src/pages/subsections/backgroundInformation/EmploymentHistory.jsx
> +  const [comapanyAddress, setCompanyAddress] = useState("");
*companyAddress

2022-07-27 20:18 UTC, MisheelSodgerel commented on onboard/src/pages/subsections/backgroundInformation/EmploymentHistory.jsx
> +  const [jobTitleHelper, setJobIitleHelper] = useState("");
*setJobTitleHelper

2022-07-27 20:19 UTC, MisheelSodgerel commented on onboard/src/pages/subsections/backgroundInformation/EmploymentHistory.jsx
> +  const [companyError, setComapnyError] = useState(false);
*setCompanyError

2022-07-27 20:20 UTC, MisheelSodgerel commented on onboard/src/pages/subsections/backgroundInformation/EmploymentHistory.jsx
> +  function handleChnage(event) {
*handleChange(event)

2022-07-27 20:20 UTC, MisheelSodgerel commented on onboard/src/pages/subsections/backgroundInformation/EmploymentHistory.jsx
> +        setComapnyError(false);
*setCompanyError(false)

2022-07-27 20:20 UTC, MisheelSodgerel commented on onboard/src/pages/subsections/backgroundInformation/EmploymentHistory.jsx
> +        setComapnyError(true);
setCompanyError(true);

2022-07-27 20:21 UTC, MisheelSodgerel commented on onboard/src/pages/subsections/backgroundInformation/EmploymentHistory.jsx
> +      setJobIitle(val);
setJobTitle(val);

2022-07-27 20:21 UTC, MisheelSodgerel commented on onboard/src/pages/subsections/backgroundInformation/EmploymentHistory.jsx
> +        setJobIitleHelper("");
setJobTitleHelper("");

2022-07-27 20:21 UTC, MisheelSodgerel commented on onboard/src/pages/subsections/backgroundInformation/EmploymentHistory.jsx
> +        setJobIitleHelper(
setJobTitleHelper

2022-07-27 20:22 UTC, MisheelSodgerel commented on onboard/src/pages/subsections/backgroundInformation/EmploymentHistory.jsx
> +                onChangeHandler={handleChnage}
*handeChange

2022-07-27 20:23 UTC, MisheelSodgerel commented on onboard/src/pages/subsections/backgroundInformation/EmploymentHistory.jsx
> +                value={comapanyAddress}
*companyAddress

2022-07-27 20:23 UTC, MisheelSodgerel commented on onboard/src/pages/subsections/backgroundInformation/EmploymentHistory.jsx
> +                onChangeHandler={handleChnage}
*handleChange

2022-07-27 20:23 UTC, MisheelSodgerel commented on onboard/src/pages/subsections/backgroundInformation/EmploymentHistory.jsx
> +                onChangeHandler={handleChnage}
*handleChange

2022-07-27 20:24 UTC, MisheelSodgerel commented on onboard/src/pages/subsections/backgroundInformation/EmploymentHistory.jsx
> +                onChangeHandler={handleChnage}
*handleChange

2022-07-27 20:24 UTC, MisheelSodgerel commented on onboard/src/pages/subsections/backgroundInformation/EmploymentHistory.jsx
> +                onChangeHandler={handleChnage}
*handleChange

2022-07-27 20:24 UTC, MisheelSodgerel commented on onboard/src/pages/subsections/backgroundInformation/EmploymentHistory.jsx
> +                onChangeHandler={handleChnage}
*handleChange

2022-07-27 20:25 UTC, MisheelSodgerel commented on onboard/src/pages/subsections/backgroundInformation/EmploymentHistory.jsx
> +  const [jobTitle, setJobIitle] = useState("");
*setJobTitle

2022-07-27 20:28 UTC, MisheelSodgerel requested changes
added comments about spelling

2022-07-27 20:36 UTC, MisheelSodgerel approved these changes

2022-07-27 20:37 UTC, MisheelSodgerel approved these changes

2022-07-28 19:44 UTC, MatthewBackes approved these changes

2022-07-28 20:03 UTC, merged